import Head from 'next/head'
import Image from 'next/image'
import classictee from '../public/classic-tee.jpg'


export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Moustache Republic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <div className='header'>
          My Cart (4)
      </div>
      <div className='columncontainer'>
        <div className='rowimg'>
          <div className='imagecontainer'>
            <Image src={classictee}></Image>
          </div>
        </div>
        <div className='row'>
            <div className='classictee'> Classic Tee</div>
            <hr></hr>
            <div><b>$75.00</b></div>
            <hr></hr>
            <div className='text'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</div>
            <div className='flex'>
              <div className='size'>SIZE</div>
              <div className='as'>*</div>
            </div>
           
            <button className='buttonsize'>S</button>
            <button className='buttonsize'>M</button>
            <button className='buttonsize'>L</button> <br></br>
            <button className='addtocart'> ADD TO CART </button>
        </div>
        

      </div>
     
    </div>
    </div>
  )
}
